### ISSUE TITLE
coc-thrift seems not enable

### ISSUE THREAD

**Issue by zhufx** [cposture/coc-thrift-syntax-support#1]
Hello~
After I use ":CocInstall coc-thrift-syntax-support" install the extensions, I use 'gd' to jump to the definition in thrift file.
It cames error like 'definition provider not found for current buffer, your language server doesn't support it'.
So, Is there any other step to configure language server in coc configure file? 
Look forward your reply, thx~

**Comment by cposture** [comment]
hello, You need to make sure that you are editing a file, not a buffer, or whether your file is .thrift~
