### ISSUE TITLE
Update coc.nvim, coc-thrift-syntax-support complete error occurred

### ISSUE THREAD

**Issue by genmzy** [cposture/coc-thrift-syntax-support#2]
```log
Complete coc-thrift-syntax-support error: Cannot read properties of null (reading '' addtionalTextEdits'')
```
![image](https://user-images.githubusercontent.com/38545714/151167596-b9ad535e-ee83-4256-bc35-8d2f0383b11d.png)
- Updating coc.nvim to latest version, editing a thrift file and triggering complete will make error.
- Thrift go-definition will jump to the line before the real definition.

**Comment by cposture** [comment]
I can not reproduce this problem
